### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Huskydog9988**
We need every contributor to sign off on this before its accepted.

### CODE REVIEW

**Comment by Huskydog9988** [comment]
@IMS212 @MCRcortex @NeRdTheNed @haydenwalker980 @SylvKT Please responded saying you agree to the project being licensed under MIT.

**Comment by MCRcortex** [comment]
i aprove

**Review by MCRcortex — APPROVED** [review]

**Review by SylvKT — APPROVED** [review]
arr :pirate_flag:

**Comment by mica-alex** [comment]
Looks good + I agree.

**Comment by IMS212** [comment]
i agree

**Review by SticksDev — APPROVED** [review]

**Comment by haydenwalker980** [comment]
LGTM

**Review by haydenwalker980 — APPROVED** [review]
i forgot to approve the thing, still LGTM

**Comment by NeRdTheNed** [comment]
Hey all, sorry I haven't responded yet! I approve.

**Review by NeRdTheNed — APPROVED** [review]

**Pull request merged**
